### PR TITLE
PDI-8731 - Cassandra SSTable Output (bulkloader) step does not work with Cassandra 1.1.x

### PR DESCRIPTION
**Pull request by pavel-sakun**
Add missing dependencies
Add support for cassandra 2.x
Split writer into CQL2 and CQL3 specific ones
Try preventing JVM from exit in case issues with cassandra config
Fixes for CQL2 writer:
 - read partitioner from config, use Murmur3Partitioner by default
 - store date as longs

### CODE REVIEW

**Comment by stepanovdg** [comment]
@m-a-hall @hudak @brosander @mattyb149 Update.

**Comment by dkincade** [comment]
Please update with unit tests....

**Comment by stepanovdg** [comment]
Updated with tests. Attached pull-request.

**Comment by pavel-sakun** [comment]
Closing in favor of https://github.com/pentaho/pentaho-cassandra-plugin/pull/54

**Pull request closed without merging**
